CREATE TABLE IF NOT EXISTS books(
	Id INT (10) AUTO_INCREMENT PRIMARY KEY,
    Author LONGTEXT,
    LaunchDate DATETIME(6) NOT NULL,
    Price DECIMAL(65,2) NOT NULL,
    Title LONGTEXT
)ENGINE=InnoDb 

